# config配置
server:
  port: 8081

spring:
  application:
    name: config

my:
  jdbcDriver: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/test
  jdbcUserName: root
  jdbcPassword: 123456






