# kafka配置
server:
  port: 8081

spring:
  application:
    name: kafka
  kafka:
    # 指定kafka代理地址,可以多个
    bootstrap-servers: 192.168.136.129:9092
    consumer:
      # 指定默认消费者group id
      group-id: group1
      auto-offset-reset: earliest





