# shiro配置
server:
  port: 8084

spring:
  application:
    name: shiro
  # 数据库连接池配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      # 初始化大小,最小,最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间,单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache,并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
      filter: stat,wall,log4j
  # redis配置
  redis:
    host: 192.168.136.136
    port: 6379
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  # 禁用thymeleaf缓存
  thymeleaf:
    cache: false
  # 缓存配置
  cache:
    type: redis
    cache-names: platform-shiro

mybatis-plus:
  # 如果是放在src/main/java目录下classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mybatis/**/*Dao.xml
  # 实体扫描,多个package用逗号或者分号分隔
  typeAliasesPackage: com.ming.shiro.domain
  global-config:
    # 主键类型(0:"数据库ID自增",1:"用户输入ID",2:"全局唯一ID(数字类型唯一ID)",3:"全局唯一ID UUID";)
    id-type: 3
    # 字段策略(0:"忽略判断",1:"非NULL判断"),2:"非空判断")
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # mp2.3+ 全局表前缀 mp_
#    table-prefix: mp_
    # 刷新mapper调试神器
#    refresh-mapper: true
    # 数据库大写下划线转换
#    capital-mode: true
    # Sequence序列接口实现类配置
#    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    # 逻辑删除配置(下面3个配置)
#    logic-delete-value: 1
#    logic-not-delete-value: 0
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    # 自定义填充策略接口实现
#    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    # 配置返回数据库(column下划线命名&&返回java实体是驼峰命名),自动匹配无需as(没开启这个,SQL需要写as:select user_id as userId)
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 配置JdbcTypeForNull,oracle数据库必须配置
#    jdbc-type-for-null: 'null'

# 日志
# 日志配置
logging:
  pattern:
    console: "-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%1.15t]){faint} %clr(%-10.40logger{39}){cyan} %clr(:){faint}  [%F:%L]  %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
  level:
    root: info
    org:
      mybatis: debug
      springframework:
        boot: info
        security: DEBUG

