# elasticsearch配置
server:
  port: 8081

spring:
  application:
    name: elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 192.168.136.129:9300
      repositories:
        enabled: true
























